{"name": "5.查询用户权限-无权限用户", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace": "self = <Response [500]>, kwargs = {}\n\n    def json(self, **kwargs):\n        r\"\"\"Returns the json-encoded content of a response, if any.\n    \n        :param \\*\\*kwargs: Optional arguments that ``json.loads`` takes.\n        :raises requests.exceptions.JSONDecodeError: If the response body does not\n            contain valid json.\n        \"\"\"\n    \n        if not self.encoding and self.content and len(self.content) > 3:\n            # No encoding set. JSON RFC 4627 section 3 states we should expect\n            # UTF-8, -16 or -32. Detect which one to use; If the detection or\n            # decoding fails, fall back to `self.text` (using charset_normalizer to make\n            # a best guess).\n            encoding = guess_json_utf(self.content)\n            if encoding is not None:\n                try:\n                    return complexjson.loads(self.content.decode(encoding), **kwargs)\n                except UnicodeDecodeError:\n                    # Wrong UTF codec detected; usually because it's not UTF-8\n                    # but some other 8-bit codec.  This is an RFC violation,\n                    # and the server didn't bother to tell us what codec *was*\n                    # used.\n                    pass\n                except JSONDecodeError as e:\n                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n    \n        try:\n>           return complexjson.loads(self.text, **kwargs)\n\n..\\..\\Pyproject\\testProject\\venv\\Lib\\site-packages\\requests\\models.py:974: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\seeki\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py:346: in loads\n    return _default_decoder.decode(s)\nC:\\Users\\seeki\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:337: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <json.decoder.JSONDecoder object at 0x0000020DC3BE5610>\ns = '<!doctype html><html lang=\"en\"><head><title>HTTP Status 500 – Internal Server Error</title><style type=\"text/css\">bod...e of the root cause is available in the server logs.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.63</h3></body></html>'\nidx = 0\n\n    def raw_decode(self, s, idx=0):\n        \"\"\"Decode a JSON document from ``s`` (a ``str`` beginning with\n        a JSON document) and return a 2-tuple of the Python\n        representation and the index in ``s`` where the document ended.\n    \n        This can be used to decode a JSON document from a string that may\n        have extraneous data at the end.\n    \n        \"\"\"\n        try:\n            obj, end = self.scan_once(s, idx)\n        except StopIteration as err:\n>           raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nC:\\Users\\seeki\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:355: JSONDecodeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_user_permissions.TestUserManager object at 0x0000020DF92B14C0>\ncase_info = {'baseInfo': {'api_name': '查询用户权限', 'header': {'Authorization': '${get_extract_data(token_null)}', 'Content-Type': 'ap..._extract_data(cookie_null)}'}, 'method': 'get', 'url': '/ssm_web/user/getUserPermissions'}, 'testCase': [{'json': {}}]}\n\n    @allure.story(next(c_id) + \"查询用户权限（业务场景）\")\n    @pytest.mark.run(order=4)\n    @pytest.mark.parametrize('case_info', get_testcase_yaml(\"./testcase/Business Scenario/user_permissions_data.yaml\"))\n    def test_user_permissions(self, case_info):\n        allure.dynamic.title(case_info['testCase'][0]['case_name'])\n>       RequestBase().specification_yaml(case_info)\n\ntestcase\\Business Scenario\\test_user_permissions.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nbase\\apiutil_business.py:149: in specification_yaml\n    raise e\nbase\\apiutil_business.py:124: in specification_yaml\n    allure.attach(self.allure_attach_response(res.json()), '接口响应信息', allure.attachment_type.TEXT)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Response [500]>, kwargs = {}\n\n    def json(self, **kwargs):\n        r\"\"\"Returns the json-encoded content of a response, if any.\n    \n        :param \\*\\*kwargs: Optional arguments that ``json.loads`` takes.\n        :raises requests.exceptions.JSONDecodeError: If the response body does not\n            contain valid json.\n        \"\"\"\n    \n        if not self.encoding and self.content and len(self.content) > 3:\n            # No encoding set. JSON RFC 4627 section 3 states we should expect\n            # UTF-8, -16 or -32. Detect which one to use; If the detection or\n            # decoding fails, fall back to `self.text` (using charset_normalizer to make\n            # a best guess).\n            encoding = guess_json_utf(self.content)\n            if encoding is not None:\n                try:\n                    return complexjson.loads(self.content.decode(encoding), **kwargs)\n                except UnicodeDecodeError:\n                    # Wrong UTF codec detected; usually because it's not UTF-8\n                    # but some other 8-bit codec.  This is an RFC violation,\n                    # and the server didn't bother to tell us what codec *was*\n                    # used.\n                    pass\n                except JSONDecodeError as e:\n                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n    \n        try:\n            return complexjson.loads(self.text, **kwargs)\n        except JSONDecodeError as e:\n            # Catch JSON-related errors and raise as requests.JSONDecodeError\n            # This aliases json.JSONDecodeError and simplejson.JSONDecodeError\n>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nE           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\n..\\..\\Pyproject\\testProject\\venv\\Lib\\site-packages\\requests\\models.py:978: JSONDecodeError"}, "attachments": [{"name": "接口地址：http://47.113.145.175:8080/ssm_web/user/getUserPermissions", "source": "613d484b-c8fb-4ea3-bd82-191dfb252798-attachment.attach"}, {"name": "接口名：查询用户权限", "source": "97009b84-7200-45b6-9ae5-8599c0bebb09-attachment.attach"}, {"name": "请求方法：get", "source": "e33f0900-cc69-48a2-86b9-fc207f289bab-attachment.attach"}, {"name": "请求头：{'Content-Type': 'application/json', 'Authorization': 'fbaa71e4-0c6a-42a7-aa44-2e7fbfc434dc', 'Cookie': 'JSESSIONID=0EA9055F87A36AD47DB82E0C8B2CBA8F'}", "source": "f9c82f99-308f-4b37-a49e-6824adda8f60-attachment.txt", "type": "text/plain"}, {"name": "请求头信息", "source": "27b9be39-2812-4352-bf37-b6ac927113c6-attachment.txt", "type": "text/plain"}, {"name": "测试用例名称：5.查询用户权限-无权限用户", "source": "96807523-f448-409a-a699-c283e8d28109-attachment.txt", "type": "text/plain"}, {"name": "请求参数", "source": "ae3eb211-5a5b-41dd-b009-ff8fb885f15f-attachment.txt", "type": "text/plain"}, {"name": "接口响应信息", "source": "e3b9111f-6c68-4a75-a820-d2ba41f984dd-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "611f0a7a-dabf-4221-ae9c-f9448b8451c0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_info", "value": "{'baseInfo': {'api_name': '查询用户权限', 'url': '/ssm_web/user/getUserPermissions', 'method': 'get', 'header': {'Content-Type': 'application/json', 'Authorization': '${get_extract_data(token_null)}', 'Cookie': '${get_extract_data(cookie_null)}'}}, 'testCase': [{'case_name': '5.查询用户权限-无权限用户', 'json': {}, 'validation': [{'eq': {'status_code': 200}}, {'eq_db': {'${get_extract_data(resourceId_null)}': []}}], 'extract_list': {'resourceId_null': '$..resourceList[*].id'}}]}"}], "start": 1749971008686, "stop": 1749971008785, "uuid": "01a6a881-9800-4d59-94cd-51b23ca25590", "historyId": "b2f519ee3bd7feb5b365093df1d2e042", "testCaseId": "c79c6433229e734fca7ed02fdc44acaa", "fullName": "testcase.Business Scenario.test_user_permissions.TestUserManager#test_user_permissions", "labels": [{"name": "feature", "value": "M02_用户管理"}, {"name": "story", "value": "C02_查询用户权限（业务场景）"}, {"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "testcase.Business Scenario"}, {"name": "suite", "value": "test_user_permissions"}, {"name": "subSuite", "value": "TestUserManager"}, {"name": "host", "value": "SQG"}, {"name": "thread", "value": "27516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Business Scenario.test_user_permissions"}]}